[tool.poetry]
name = "fbutils"
version = "0.1.1"
description = ""
authors = ["Denis Kust <denis@denis>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
firebird-driver = "^1.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
